name: build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get entire git tree, required for nerdbank gitversioning
      - name: Get version
        shell: pwsh
        run: |
          cd src
          $version = (nbgv get-version -f json | ConvertFrom-Json).SimpleVersion
          Write-Host "Version $version"
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build the hello-docker Docker image
      #   run: |
      #     docker build . --tag ghcr.io/g3rv4/fakerelay:latest
      #     docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
      #     docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest